[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
app_core = { path = "../app_core" }
common = { path = "../common" }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
async-trait = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
